stub step execution

diff --git a/bin/anyci-ci b/bin/anyci-ci
--- a/bin/anyci-ci
+++ b/bin/anyci-ci
@@ -15,5 +15,33 @@ ANYCI_GROUP="${ANYCI_GROUP:-default}"
 lib/require/dir "$PROJECT_ROOT" "$ANYCI_ROOT/family/$ANYCI_FAMILY" "$ANYCI_ROOT/group/$ANYCI_GROUP"
 lib/set/search_paths "${ANYCI_PROJECT_PATHS:-ci:pipeline}"
 
-step_file=$(lib/lookup "foo" "step") || log "failed to find step"
-log "foo"
+# if steps are provided, e.g. 'bin/ci' versus 'bin/ci foo', these will execute
+ANYCI_DEFAULT_STEPS=(
+  check
+  build
+  test
+)
+
+case "$1" in
+  -h|--help|help)
+    lib/help ;;
+  -v|--version|version)
+    lib/version ;;
+  exec)
+    exec "$ANYCI_ROOT/bin/exec" "$@"
+    ;;
+  *)
+    [ $# -eq 0 ] && set -- "${ANYCI_DEFAULT_STEPS[@]}"
+    ;;
+esac
+
+# step execution
+log "step(s) to execute:" "$@"
+for step in "$@"; do
+  step_file=$(lib/lookup "$step") || die "failed to find '$step' step"
+  [ -x "$step_file" ] || die "$step_file must be executable!"
+
+  log "executing step: $step"
+  cd "$PROJECT_ROOT"
+  "$ANYCI_ROOT/bin/exec" "$step_file"
+done
